swagger: "2.0"
info:
  description: "これはEAGIS_BACKENDに関するAPIです。"
  version: "1.0.0"
  title: "EAGIS_BACKEND API"
  
paths:
  /member/entry/{name}:
    get:
      summary: "現在のメンバー情報API"
      description: "指定された名前の情報を返します"
      parameters:
      - name: "name"
        in: "path"
        description: "現在の情報を取得したい人の名前"
        required: true
        type: "string"
        format: "example"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "nnnnn"
              entry_time:
                type: "string"
                example: "yyyy-mm-dd hh:mm:ss"
              update_time:
                type: "string"
                example: "yyyy-mm-dd hh:mm:ss"
              room:
                type: "string"
                example: "111"
              devices:
                type: "string"
                example: "iPhone"
  /member/log/{name}:
    get:
      summary: "過去のメンバー情報API"
      description: "指定された名前の情報を返します"
      parameters:
      - name: "name"
        in: "path"
        description: "過去の情報を取得したい人の名前"
        required: true
        type: "string"
        format: "example"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                name:
                  type: "string"
                  example: "nnnnn"
                entry_time:
                  type: "string"
                  example: "yyyy-mm-dd hh:mm:ss"
                exit_time:
                  type: "string"
                  example: "yyyy-mm-dd hh:mm:ss"
                room:
                  type: "string"
                  example: "111"
                devices:
                  type: "string"
                  example: "iPhone"
      
      
      
      
